name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install and start virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb python3-tk
        Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:0
        echo "Virtual display started"      

    - name: Install pytest
      run: |
        pip install pytest 

    - name: test 1
      id: a-command-test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Random     
        command: DISPLAY=:0 pytest -k test_random_one_color
        timeout: 10
        max-score: 1

    - name: test 2
      id: a-command-test-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Alternate Lines       
        command: DISPLAY=:0 pytest -k test_alternate_lines
        timeout: 10
        max-score: 1

    - name: test 3
      id: a-command-test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test White Line        
        command: DISPLAY=:0 pytest -k test_white_line
        timeout: 10
        max-score: 1

    - name: test 4
      id: a-command-test-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Decode Image        
        command: DISPLAY=:0 pytest -k test_decode_image
        timeout: 10
        max-score: 1
        
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        A-COMMAND-TEST-1_RESULTS: "${{steps.a-command-test-1.outputs.result}}"
        A-COMMAND-TEST-2_RESULTS: "${{steps.a-command-test-2.outputs.result}}"
        A-COMMAND-TEST-3_RESULTS: "${{steps.a-command-test-3.outputs.result}}"
        A-COMMAND-TEST-4_RESULTS: "${{steps.a-command-test-4.outputs.result}}"
      with:
        runners: a-command-test-1,a-command-test-2,a-command-test-3,a-command-test-4
