name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install and start virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "Virtual display started"      
    - name: pytest
      id: pytest
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 4
        setup-command: export DISPLAY=:0
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTEST_RESULTS: "${{steps.pytest.outputs.result}}"
      with:
        runners: pytest
